---
abstract: 'A modern LWPx::ParanoidAgent for safer requests'
author:
  - 'Thomas Sibley <tsibley@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  HTTP::Server::PSGI: 0
  Test::Requires: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LWP-UserAgent-Paranoid
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  LWPx::ParanoidHandler: 0
  Net::DNS::Paranoid: 0
  Scalar::Util: 0
  Time::HiRes: '1.9716'
  Perl: 5.006
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/lwp-useragent-paranoid.git
version: '0.97'
